name: CI on Self-Hosted Runner

on:
  push:
    branches:
      - main   # sirf main branch par push hone pe 
  workflow_dispatch:  # optional: manual bhi allow 

jobs:
  test:
    runs-on: [self-hosted, ec2]   # yeh aapke EC2 ko ko target karega
    steps:
      - name: Print message
        run: echo "✅ Self-Hosted Runner triggered successfully!"

      - name: Show system info
        run: uname -a

      - name: List repo files
        run: ls -l
